"""
Generate docker-compose.yml for ANY cluster topology — no hand-editing.

Usage:
    python gen_compose.py 3,2      # cluster1 = 3 nodes, cluster2 = 2 nodes
    python gen_compose.py 3        # single cluster of 3 (the default setup)
    python gen_compose.py          # interactive prompt

Convention (same as swarm_launcher.py): in a cluster of N nodes, 1 is elected
leader and N-1 train, so --num_workers = N-1. Minimum 2 nodes per cluster.

It writes docker-compose.yml, then just run:  docker compose up --build -d
"""
import sys

REGIONS = ["us-east", "eu-west", "ap-south", "us-west", "eu-north"]

HEADER = """# AUTO-GENERATED by gen_compose.py (topology: {topology}). Re-run the generator
# to change the topology instead of editing this file by hand.

x-node-common: &node-common
  image: secure-fl:latest
  depends_on:
    global-server:
      condition: service_healthy
  networks: [flnet]
  restart: on-failure

x-node-env: &node-env
  GLOBAL_SERVER_URL: http://global-server:8000
  DISCOVERY_MODE: registry
  REGISTRY_POLL_INTERVAL: "2"
  API_PORT: "5001"

services:
  global-server:
    build: .
    image: secure-fl:latest
    container_name: global-server
    environment:
      REGISTRY_TTL: "20"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/')"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [flnet]
"""

NODE_TMPL = """
  {name}:
    <<: *node-common
    container_name: {name}
    environment:
      <<: *node-env
      NODE_HOST: {name}
    command: ["python", "-m", "nodes.node",
              "--cluster_id", "{cluster}", "--port", "4001",
              "--region", "{region}", "--latency", "{latency}",
              "--client_id", "{client_id}", "--num_workers", "{num_workers}"]
"""

# Observability stack: Prometheus scrapes global-server:8000/metrics, Grafana
# reads Prometheus. Both are auto-provisioned (datasource + dashboard), so you
# just open http://localhost:3000 and the FL dashboard is already there.
MONITORING = """
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks: [flnet]
    restart: on-failure

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on: [prometheus]
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    networks: [flnet]
    restart: on-failure
"""

FOOTER = """
networks:
  flnet:
    driver: bridge
"""


def parse_topology(argv):
    if len(argv) > 1:
        counts = [int(x) for x in argv[1].split(",") if x.strip()]
    else:
        n = int(input("How many clusters? ").strip())
        counts = [int(input(f"  Cluster {i + 1}: how many nodes? ").strip()) for i in range(n)]
    for i, c in enumerate(counts):
        if c < 2:
            raise SystemExit(f"Cluster {i + 1} has {c} node(s); need >= 2 (1 leader + >=1 worker).")
    return counts


def main():
    counts = parse_topology(sys.argv)
    topo = ",".join(str(c) for c in counts)

    out = HEADER.format(topology=topo)
    for ci, count in enumerate(counts, start=1):
        cluster = f"cluster{ci}"
        region = REGIONS[(ci - 1) % len(REGIONS)]
        for j in range(1, count + 1):
            out += NODE_TMPL.format(
                name=f"{cluster}-node{j}",
                cluster=cluster,
                region=region,
                latency=10 * j,
                client_id=j,
                num_workers=count - 1,   # leader excluded
            )
    out += MONITORING
    out += FOOTER

    with open("docker-compose.yml", "w", encoding="utf-8") as f:
        f.write(out)

    print(f"Wrote docker-compose.yml | clusters={len(counts)} | nodes={sum(counts)} | topology={topo}")
    print("Next:  docker compose up --build -d")


if __name__ == "__main__":
    main()
